group: travis_latest
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: python
cache: pip
python:
  #- 2.7
  #- 3.4
  #- 3.5
  #- 3.6
  - 3.7
matrix:
  allow_failures:
    - python: 2.7
    - python: nightly
    - python: pypy
    - python: pypy3
env:
  - REPO=OWASP/CheatSheetSeries
  - REPO=jarun/ddgr
  - REPO=seungwonpark/RandWireNN
  - REPO=USTC-Resource/USTC-Course
  - REPO=imhuay/Algorithm_Interview_Notes-Chinese
  - REPO=Avik-Jain/100-Days-Of-ML-Code
  - REPO=vinta/awesome-python
  - REPO=zhaoolee/ChromeAppHeroes
  - REPO=tensorflow/models
  - REPO=hardikvasa/google-images-download
  - REPO=CriseLYJ/awesome-python-login-model
  - REPO=ageitgey/face_recognition
  - REPO=OUCMachineLearning/OUCML
  - REPO=toddmotto/public-apis
  - REPO=TheAlgorithms/Python
  - REPO=facebookresearch/PyTorch-BigGraph
  - REPO=donnemartin/system-design-primer
  - REPO=NVlabs/stylegan
  - REPO=google-research/bert
  - REPO=Microsoft/pyright
  - REPO=scikit-learn/scikit-learn
  - REPO=django/django
  - REPO=soimort/you-get
  - REPO=keras-team/keras
  - REPO=geekinglcq/CDCS
  - REPO=PythonCharmers/python-future
  - REPO=ansible/ansible
  - REPO=Tribler/tribler
  - REPO=oaubert/python-vlc
  - REPO=ColdGrub1384/Pyto
  - REPO=getsentry/sentry
  - REPO=CoreSecurity/impacket
  - REPO=nodejs/node
  - REPO=nodejs/node-gyp
  - REPO=internetarchive/openlibrary
  - REPO=google/ffn
  - REPO=webpy/webpy
  - REPO=ibm-watson-iot/connector-cloudant
  - REPO=ibm-watson-iot/device-kodi
  - REPO=ArduPilot/ardupilot
  - REPO=matplotlib/matplotlib
  - REPO=ckan/ckan
  - REPO=ggtracker/sc2reader
  - REPO=apache/beam
  - REPO=apache/incubator-mxnet
  - REPO=apache/spark
  - REPO=ibm-watson-iot/functions
install:
  #- pip install -r requirements.txt
  - pip install mypy  # pytest  # add other testing frameworks later
before_script:
  - URL=https://github.com/${REPO}
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - git clone --depth=50 ${URL} ~/${REPO}  # --branch=master
  - cd ~/${REPO}
script:
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - time mypy
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
